# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20161205_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='question',
            new_name='questions',
        ),
        migrations.AddField(
            model_name='profile',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='short_text',
            field=models.TextField(default='', max_length=85),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/default-user-image.png', null=True, upload_to='avatar/'),
        ),
    ]
